# Generated by Django 4.0.2 on 2022-04-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30, verbose_name='Désignation')),
                ('head_agency', models.CharField(max_length=50, verbose_name='Nom complet de Chef')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Numero de téléphone')),
                ('address', models.TextField(max_length=250, verbose_name='Adresse ')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nom')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nom')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nom')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.city', verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordind', models.CharField(max_length=40, verbose_name='Libellé')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordind', models.CharField(max_length=40, verbose_name='Libellé')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nom de famille')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prénom(s)')),
                ('birth_day', models.DateField(verbose_name='Date de naissance')),
                ('birth_place', models.CharField(max_length=30, verbose_name='Lieu de naissance')),
                ('profession', models.CharField(max_length=30, verbose_name='Profession')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Numero de téléphone')),
                ('address', models.TextField(max_length=250, verbose_name='Adresse ')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.city', verbose_name='Ville actuelle')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.district', verbose_name='Quartier actuel')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(max_length=400, unique=True, verbose_name='UID')),
                ('address', models.TextField(max_length=400, verbose_name='Adresse')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.city', verbose_name='Ville actuelle')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.district', verbose_name='Quartier actuel')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordind', models.CharField(max_length=40, verbose_name='Libellé')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=40, verbose_name='Nom système')),
                ('name', models.CharField(max_length=40, verbose_name='Nom')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=30, verbose_name='Modèle')),
                ('power', models.BigIntegerField(verbose_name='Puissance')),
                ('empty_weight', models.BigIntegerField(verbose_name='Poids à vide')),
                ('pay_load', models.BigIntegerField(verbose_name='Charge utile')),
                ('uid_tag_rfid', models.TextField(null=True, unique=True, verbose_name='UID du tag RFID')),
                ('plate_number', models.TextField(max_length=30, unique=True, verbose_name="Numéro d'immatriculation")),
                ('status', models.CharField(max_length=30, verbose_name='Statut')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('energy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.energy', verbose_name='Energie')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.gender', verbose_name='Genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.owner', verbose_name='Propriétaire')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.type', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=40, verbose_name='Nom système')),
                ('name', models.CharField(max_length=40, verbose_name='Nom')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, max_length=20000, null=True, upload_to='uploads/images/', verbose_name='Photo de profil'),
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=40, verbose_name='Motif')),
                ('desciption', models.TextField(max_length=400, verbose_name='Description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.vehicle', verbose_name='Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('uid_reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.reader', to_field='uid', verbose_name='UID du lecteur')),
                ('uid_vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.vehicle', to_field='uid_tag_rfid', verbose_name='UID du Vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.vehicle', verbose_name='Vehicule'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=40, null=True, verbose_name='Motif')),
                ('desciption', models.TextField(max_length=400, null=True, verbose_name='Description')),
                ('done_at', models.DateField(null=True, verbose_name='Date')),
                ('validity', models.IntegerField(null=True, verbose_name='Validité')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.agency', verbose_name='Agence')),
                ('typeOperation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.typeoperation', verbose_name="type d'operation")),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.vehicle', verbose_name='Vehicule')),
                ('verdict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.verdict', verbose_name='Verdict')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400, verbose_name='Message')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.record', verbose_name='Enregistrement')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.department', verbose_name='Departement'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.city', verbose_name='Ville actuelle'),
        ),
        migrations.AddField(
            model_name='agency',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.district', verbose_name='Quartier actuel'),
        ),
        migrations.AddField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safecar.agency', verbose_name='Service parent'),
        ),
    ]
