# Generated by Django 4.0.4 on 2022-04-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0002_agency_city_department_district_energy_gender_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='designation',
            field=models.CharField(max_length=50, verbose_name='Désignation'),
        ),
    ]
