# Generated by Django 4.0.4 on 2022-04-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0003_alter_agency_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy',
            old_name='wordind',
            new_name='wording',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='wordind',
            new_name='wording',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='wordind',
            new_name='wording',
        ),
    ]
