# Generated by Django 4.0.4 on 2022-04-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0004_rename_wordind_energy_wording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safecar.agency', verbose_name='Service parent'),
        ),
    ]
