# Generated by Django 4.0.4 on 2022-04-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0005_alter_agency_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safecar.agency', verbose_name='Service parent'),
        ),
    ]
