# Generated by Django 4.0.4 on 2022-04-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0007_agency_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=40, unique=True, verbose_name='Non systeme')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nom')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.usergroup', verbose_name='Groupe parent')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='UserGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.usergroup', verbose_name="Groupe d'utilisateur"),
        ),
    ]
