# Generated by Django 4.0.4 on 2022-04-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0009_alter_usergroup_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserGroup',
            new_name='user_group',
        ),
    ]
