# Generated by Django 4.0.4 on 2022-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0010_rename_usergroup_user_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='birth_day',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='owner',
            name='sex',
            field=models.CharField(default=None, max_length=20, verbose_name='Sexe'),
            preserve_default=False,
        ),
    ]
