# Generated by Django 4.0.4 on 2022-05-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0012_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='reader',
            name='designation',
            field=models.CharField(default=1, max_length=50, verbose_name='Désignation'),
            preserve_default=False,
        ),
    ]
