# Generated by Django 4.0.4 on 2022-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0013_remove_reader_vehicle_reader_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='typeOperation',
            new_name='type_operation',
        ),
    ]
