# Generated by Django 4.0.4 on 2022-05-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0016_rename_desciption_warning_description_warning_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='done_at',
            field=models.DateField(null=True, verbose_name='Date du constat'),
        ),
    ]
