# Generated by Django 4.0.4 on 2022-05-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0017_warning_done_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=40, unique=True, verbose_name='Non systeme')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nom')),
                ('entity', models.CharField(max_length=40, verbose_name='Entité')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safecar.status', verbose_name='Status'),
        ),
    ]
