# Generated by Django 4.0.4 on 2022-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0018_status_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
