# Generated by Django 4.0.4 on 2022-05-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0020_alter_vehicle_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='uid_reader',
            new_name='reader',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='uid_vehicule',
            new_name='vehicle',
        ),
    ]
