# Generated by Django 4.0.4 on 2022-05-12 15:27

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0021_rename_uid_reader_record_reader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_expired',
            field=computed_property.fields.ComputedBooleanField(compute_from='__is_expired', default=False, editable=False),
        ),
    ]
