# Generated by Django 4.0.4 on 2022-05-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecar', '0025_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='reader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safecar.reader', to_field='uid', verbose_name='UID du lecteur'),
        ),
        migrations.AlterField(
            model_name='record',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safecar.vehicle', to_field='uid_tag_rfid', verbose_name='UID du Vehicule'),
        ),
    ]
